### ISSUE TITLE
ROADMAP - Assistente Digital - @TECAbot

### ISSUE THREAD

**Issue by uira** [R4dar/InteligenciaColetivaBot#4]
- [ ] Gestão de Grupos #3 
- [ ] ChatBot multiplataforma (xmpp, mirc, telegram, facebook messenger, whatsapp
- [ ] ajuda a conectar outros aplicativos, serviços e dados;
- [ ] Configurar algoritmos
- [ ] Organizar Notificações

**Comment by uira** [comment]
@lunhg

**Comment by lunhg** [comment]
> @lunhg

[API feathers para telegram (com  swagger)](https://github.com/lunhg/Assistente/tree/master/src)

**Comment by lunhg** [comment]
> * [ 1 ]  Gestão de Grupos #3
> * [ 2 ]  ChatBot multiplataforma (xmpp, mirc, telegram, facebook messenger, whatsapp
> * [ 3 ]  ajuda a conectar outros aplicativos, serviços e dados;
> * [ ]  Configurar algoritmos
> * [ 4 ]  Organizar Notificações

# 1

Existe uma tabela de [base de dados](https://github.com/lunhg/Assistente/blob/master/src/models/grupos.model.js)  e um [ponto de acesso à API](https://github.com/lunhg/Assistente/tree/master/src/services/grupos)

# 2

Em fase de testes com [Telegraf](https://github.com/lunhg/Assistente/tree/master/src/services/bot)

# 3 

Em fase de desenvolvimento, nos arquivos `src/authentication*.js` , por exemplo, [src/authentication.js](https://github.com/lunhg/Assistente/blob/master/src/authentication.js)

# 4

Notificações no telegram em fase de desenvolvimento
